# Generated by Django 4.1.2 on 2022-11-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_rename_is_user_user_is_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_doctor',
            new_name='is_mentor',
        ),
    ]
