# Generated by Django 4.1.2 on 2022-11-05 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_rename_is_doctor_user_is_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type_of_test', models.CharField(choices=[('Rapid Color Naming', 'Rapid Color Naming'), ('Reading Comprehension Test', 'Reading Comprehension Test'), ('Handwriting Recognition Test', 'Handwriting Recognition Test'), ('Object Classification Test', 'Object Classification Test')], max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.patient')),
            ],
        ),
    ]
